### PR TITLE
Call capture.output() instead of getSrcref() to read design code

### PR DESCRIPTION
**Pull request by clabima**
This addresses #50 by generating the same output for designer code attribute as before, except it does not depend on `keep_source` during package install to work.

Shinyapps.io also doesn't seem to support options when building dependencies, so moving away from getSrcref() allows shiny.io server to install and run designer function calls without issues (currently app outputs relying on design call are returning errors).

### CODE REVIEW

**Comment by nfultz** [comment]
internally, each function body is stored as an expression tree object -
`deparse` converts that back to text - that means comments and whitespace
can change.  The reason why each `{` gets its own line with deparse is that
each one is a separate node in the expression tree, and R prints a new line
for each one.

**Comment by jaspercooper** [comment]
OK that makes sense and also explains the comment issue. I hadn't noticed deparse() was ignoring comments. 

So either:
1. we rely on source code and have comments, at the cost of lots of install problems
2. we use an expression tree approach, but lose comments because they're not part of the tree
3. we rely on capture.output which will not have comments when it doesn't have the source, but should otherwise work OK, with the possible issue of changes to the environment

If I've accurately summarized the choices we face, I'd vote for 3 I think

**Comment by nfultz** [comment]
For behavior of number 3, strongly recommend writing your own helper
instead of relying on `capture.output(print(design_template))` - print is
generic and can be overrode, for example if people have crayon / colorout
loaded there can be control codes for color or other garbage in the output.
We should check if the srcref attribute is present, if so use it, otherwise
fall back to deparse.

**Comment by clabima** [comment]
I use `getSrcref()` _and_ `deparse()` if source file is not available. Built from this branch and ran fine. I don't see the advantage of having it both ways over using deparse() in all cases though.

**Comment by nfultz** [comment]
If you are falling back to deparse, you should locate the {{{ block in the expression tree directly instead of using a regex, like in the original version of this function.


```
f <- function(x){
  {FALSE}
  {{{
    step1 <- a
    step2 <- b
    step3 <- c
    step4 <- z
    design <- step1 / step2 / step3 / step4
    
  }}}
  {{FALSE}}
  {FALSE}
  x
}


find_triple_bracket <- function(f){
  
  pred <- function(expr, depth=3) {
    (depth == 0) || (
      length(expr) > 1 &&
        expr[[1]] == as.symbol('{') &&
        Recall(expr[[2]], depth - 1)
    )
  }
  
  clean <- function(ch, n=length(ch)-1) paste0(ch[2:n], collapse = "\n")
  
  ret <- Filter(pred, body(f))
  
  if(length(ret) == 0) "" else clean(deparse(ret[[1]][[2]][[2]]))
  
}

find_triple_bracket(f)
```

**Comment by nfultz** [comment]
Also on shinyapps.io, did you try setting the R_KEEP_PKG_SOURCE in Renviron or Renviron.site? It might get picked up that way- https://stackoverflow.com/questions/39084284/how-to-pass-environment-variables-to-shinyapps

**Comment by clabima** [comment]
On shinyapps.io question: yes, I tried that and did not work. Is
setting  R_KEEP_PKG_SOURCE=yes
in .Renviron enough on a Windows computer? It seems like ?Startup suggests
a different default directory for .Renviron and .Rprofile, but perhaps I'm
misreading it:

"On systems with sub-architectures (mainly Windows), the files
‘Renviron.site’ and ‘Rprofile.site’ are looked for first in
architecture-specific directories, e.g. ‘R_HOME/etc/i386/Renviron.site’.
And e.g. ‘.Renviron.i386’ will be used in preference to ‘.Renviron’."

Thanks for pointing to find_triple_bracket(), very helpful and much neater
than regex.

2018-05-25 0:00 GMT+02:00 Neal Fultz <notifications@github.com>:

**Comment by nfultz** [comment]
I would recommend opening a support ticket for shinyapps and see if they have a way of getting the env vars set at install time instead of just run time.

**Comment by jaspercooper** [comment]
OK I'm going to merge this but have to fix some of the tests that have been broken with updates to diagnose_design

**Comment by jaspercooper** [comment]
OK this is ready to go

**Pull request merged**
