### PR TITLE
Add two_arm_covariate_designer

### PR DESCRIPTION
**Pull request by jaspercooper**
# Description

Builds a design with one treatment and one control arm.
Treatment effects can be specified either by providing \code{control_mean} and \code{treatment_mean}
or by specifying a \code{control_mean} and \code{ate}.
Non random assignment is specified by a possible correlation, \code{rho_WZ},  between \code{W} and a latent variable that determines the probability of \code{Z}.  
Nonignorability is specified by a possible correlation, \code{rho_WY},  between \code{W} and outcome \code{Y}.  

# Checklist:

- [X] Designer is documented according to the [contributing guidelines](https://declaredesign.org/library/articles/how_to_write_and_contribute_designers.html) 
- [X] Designer and any vignettes have been added to overview.csv
- [X] Tests added to testthat to ensure coverage remains at 100%
- [X] Branch is passing devtools::check() with 0 errors, warnings, or notes

### CODE REVIEW

**Comment by nfultz** [comment]
You should be able to use `generics` and not `broom` with `estimatr`, fwiw

**Comment by nfultz** [comment]
`lm_lin` doesn't have a tidy method defined in estimatr: https://github.com/DeclareDesign/estimatr/blob/master/R/S3_tidy.R

We could add one I guess.

**Comment by jaspercooper** [comment]
Not sure I understand how the diagnosis and designer can work fine locally without a tidy method, and then break on Travis, though. Do you have a sense of what is generating this @nfultz ?

**Comment by clabima** [comment]
`validation_fn()` is set to error for lm_lin, even though tidy() works on lm_lin class with the current estimatr version. Should still create S3 method for lm_lin?

PR on DeclareDesign: https://github.com/DeclareDesign/DeclareDesign/compare/remove-error-message-for-lm_lin?expand=1

**Pull request merged**
